# Generated by Django 3.1 on 2020-09-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listArch', '0048_auto_20200901_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydesc',
            name='definition',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama Çevirisi'),
        ),
    ]
