# Generated by Django 3.1 on 2020-10-21 07:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listArch', '0086_auto_20201020_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='isRetail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='retail',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.CASCADE, to='listArch.company', verbose_name='Mağaza'),
        ),
        migrations.AlterField(
            model_name='list',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 10, 12, 17, 63821), verbose_name='Kayıt Tarihi'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='creationDate',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 21, 10, 12, 17, 67107), verbose_name='Kayıt Tarihi'),
        ),
    ]
